spring:
  main:
    web-application-type: none
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./target/db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    locations: classpath:/db/migration
